// app/layout.tsx
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import RealtimeAlertPopup from "@/components/RealtimeAlertPopup"
import { Toaster } from "react-hot-toast"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Community Protection App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Toast notifications */}
        <Toaster position="top-right" reverseOrder={false} />

        {/* Realtime alert popups */}
        <RealtimeAlertPopup />

        {/* Main content */}
        <main>{children}</main>
      </body>
    </html>
  )
}
